// You are given two strings s and t.

// String t is generated by random shuffling string s and then add one more letter at a random position.

// Return the letter that was added to t.

 

// Example 1:

// Input: s = "abcd", t = "abcde"
// Output: "e"
// Explanation: 'e' is the letter that was added.
//   Link:https://leetcode.com/problems/find-the-difference/description/
// Solution
class Solution {
    public char findTheDifference(String s, String t) {
        HashMap<Character,Character> chi = new HashMap<>();
        int xorResult = 0;
        for(char c : s.toCharArray()){
            xorResult ^=c;
        }
        for(char c : t.toCharArray()){
            xorResult ^=c;
        }
        return (char) xorResult;
    }
}
